<?php

/**
 * Implements hook_flush_caches().
 *
 * (Re-)register migrations here.
 */
function ucsf_it_migration_flush_caches() {

  // common arguments shared by all migrations
  $common_arguments = array(
    'source_version' => 6,
    'group' => 'ucsf_it',
    'source_connection' => 'ucsf_it_legacy', // bogus value, see "source_database" for the real deal.
    'source_database' => array(
      'driver' => 'mysql',
      'database' => 'information_technology',
      'host' => 'localhost',
      'user' => 'legacy',
      'password' => variable_get('ucsf_it_migration_password', ''),
    ),
  );
}
