<?php
/**
 * @file synonyms.inc
 */

/**
 * Taxonomy synonyms migration class for Drupal 6.
 *
 * @see DrupalTerm6Migration
 */
class UcsfItSynonyms6Migration extends DrupalMigration
{
  /**
   * @param array $arguments
   */
  public function __construct(array $arguments)
  {
    parent::__construct($arguments);
    // @todo implement
  }


  /**
   * @see DrupalMigration::query()
   * @return SelectQueryInterface
   */
  protected function query()
  {
    // @todo implement
  }
}
